name = "allura-portfolio-site"
compatibility_date = "2024-05-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

# Configure the Pages project
[pages_build_output_directory]
directory = "./dist"

# Email binding for Cloudflare Workers
[[email]]
name = "CLOUDFLARE_EMAIL"
to = "contact@zacharylincoln.com"

# Environment variables
[vars]
NODE_ENV = "production"

# Routes configuration
[[routing]]
pattern = "allura-lincoln.com/*"
zone_name = "allura-lincoln.com"

[[routing]]
pattern = "www.allura-lincoln.com/*"
zone_name = "allura-lincoln.com"
