backend:
  name: github
  branch: main # change this to your branch
  repo: zlincoln/allura-portfolio-site # change this to your repo
  site_domain: allura-lincoln.com # change this to your domain
  base_url: https://allura-lincoln.com # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration