backend:
  name: github
  branch: main # change this to your branch
  repo: zlincoln/allura-portfolio-site # change this to your repo
  site_domain: allura-lincoln.com # change this to your domain
  base_url: https://allura-lincoln.com # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration
collections:
- name: work
  label: Work
  folder: src/content/work
  create: true
  slug: '{{slug}}'
  fields:
  - {label: Title, name: title, widget: string}
  - {label: Description, name: description, widget: text}
  - {label: Image, name: image, widget: image, default: 'src/assets/images'}
  - {label: URL, name: url, widget: string}
  - {label: Tags, name: tags, widget: list}
  - {label: Date, name: date, widget: datetime}
  - {label: Featured, name: featured, widget: boolean}
  - {label: Body, name: body, widget: markdown}
- name: case-study
  label: Case Study
  folder: src/content/case-study
  create: true
  slug: '{{slug}}'
  fields:
  - {label: Title, name: title, widget: string}
  - {label: Description, name: description, widget: text}
  - {label: Image, name: image, widget: image}
  - {label: URL, name: url, widget: string}
  - {label: Tags, name: tags, widget: list}
  - {label: Date, name: date, widget: datetime}
  - {label: Featured, name: featured, widget: boolean}
  - {label: Body, name: body, widget: markdown}
- name: 'post'
  label: 'Post'
  folder: 'src/content/post'
  create: true
  fields:
  - { label: 'Title', name: 'title', widget: 'string' }
  - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
  - { label: 'Category', name: 'category', widget: 'string' }
  - {
      label: 'Tags',
      name: 'tags',
      widget: 'list',
      allow_add: true,
      allow_delete: true,
      collapsed: false,
      field: { label: 'Tag', name: 'tag', widget: 'string' },
    }
  - { label: 'Image', name: 'image', widget: 'string' }
  - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
  - { label: 'Author', name: 'author', widget: 'string' }
  - { label: 'Content', name: 'body', widget: 'markdown' }
media_folder: 'src/assets/images'
public_folder: '/_astro/'