name: Deploy to Cloudflare Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all history
          ref: ${{ github.ref }}  # Use the exact ref that triggered the workflow

      - name: Debug checkout
        run: |
          echo "Current branch: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          git log -n 1

      - name: Install & build
        env:
          OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          # Debug environment variables
          echo "=== Environment Variables ==="
          echo "OAUTH_GITHUB_CLIENT_ID: ${OAUTH_GITHUB_CLIENT_ID}"
          echo "OAUTH_GITHUB_CLIENT_SECRET: ${OAUTH_GITHUB_CLIENT_SECRET}"
          echo "CLOUDFLARE_API_KEY: ${CLOUDFLARE_API_KEY}"
          echo "CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}"
          echo "CONTACT_EMAIL: ${CONTACT_EMAIL}"
          echo "=== End Environment Variables ==="

          # Set all required environment variables
          export OAUTH_GITHUB_CLIENT_ID=${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          export OAUTH_GITHUB_CLIENT_SECRET=${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
          export CLOUDFLARE_API_KEY=${{ secrets.CLOUDFLARE_API_KEY }}
          export CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          export CONTACT_EMAIL=${{ secrets.CONTACT_EMAIL }}

          # Debug environment variables after export
          echo "=== Environment Variables After Export ==="
          echo "OAUTH_GITHUB_CLIENT_ID: $OAUTH_GITHUB_CLIENT_ID"
          echo "OAUTH_GITHUB_CLIENT_SECRET: $OAUTH_GITHUB_CLIENT_SECRET"
          echo "CLOUDFLARE_API_KEY: $CLOUDFLARE_API_KEY"
          echo "CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID"
          echo "CONTACT_EMAIL: $CONTACT_EMAIL"
          echo "=== End Environment Variables After Export ==="

          # Run the build with all variables available
          npm ci
          npm run build          # produces dist/

      - name: Upload with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=allura-portfolio-site --branch=main
          env:
            # GitHub OAuth variables for CMS
            OAUTH_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
            OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}
            
            # Cloudflare variables for email
            CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}